### ISSUE TITLE
full video url

### ISSUE THREAD

**Issue by rohanagrawal8053** [HISPlayer/Unity_Video_Player#1]
can you find the source address of this url ;- https://dxip4wcd8mhk4.cloudfront.net/drm/86920b4d-e11c-4cd9-a84a-3fd3290fa901/360p/drm-hls/master-1027465.4486280443.m3u80.ts

**Comment by jaime-hisplayer** [comment]
> can you find the source address of this url ;- https://dxip4wcd8mhk4.cloudfront.net/drm/86920b4d-e11c-4cd9-a84a-3fd3290fa901/360p/drm-hls/master-1027465.4486280443.m3u80.ts

Yes we can! Can you please contact us here: https://www.hisplayer.com/contact/
