### ISSUE TITLE
Questions about Crush Issues in Using Assets

### ISSUE THREAD

**Issue by kimJY519** [HISPlayer/Unity_Video_Player#12]
**Describe the issue**

hello.

I am developing a streaming feature using HLS URLs. I am inheriting the 'HISPlayerManager' class to develop the app.

I have developed a function that adds a video in real-time using the 'AddStream' function provided by the asset and maps it to a RawImage. 

However, I noticed that when adding a new video, the video from the previous playerIndex is mapped to the newly created RawImage for a short time. This disappears when the video finishes buffering, but it makes the RawImage look like all the video is temporarily frozen.

Also, when using 'RemoveStream' to remove the added HLS footage, the Unity Editor crashes quite often. I've tried calling the Stop function and then calling the RemoveStream function a few seconds later, just in case it's an asynchronous error with the streaming data processing, but the same thing happens.

Are you aware of this situation?

Additionally, do you have any plans to add a virtual function or callback function to let us know when the video frame is updated?

Looking forward to your response, thank you.

**Your system and development environment:**
 - HISPlayer Unity Player SDK version: 3.4.1
 - Unity version: 2020.3.0f1
 - Package URL (if purchased from the store): https://assetstore.unity.com/packages/tools/video/video-streaming-player-for-windows-283266#releases
 - Operating system (OS): Windows

**To Reproduce**
Steps to reproduce the issue:
1. 

**Screenshots**
If applicable, could you add screenshots to help explain your problem?

**Comment by Nusi-22** [comment]
Hi @kimJY519, we will review your comments and come back to you, thank you.
