### ISSUE TITLE
Some questions about the "Unity HISPlayer"

### ISSUE THREAD

**Issue by LoS-Light** [HISPlayer/Unity_Video_Player#13]
Hello, I recently used the Unity HISPlayer Trial Version and found it quite good.
I'm currently considering purchasing the "Video Streaming Player for all Platforms" on the Unity Asset Store. https://assetstore.unity.com/packages/tools/video/video-streaming-player-for-all-platforms-281535#description

However, I have a few questions below:

<hr>

[1] I’ve reviewed your official documentation, and it appears that the release versions have been updated to 4.4.0.
https://hisplayer.github.io/UnityAndroid-SDK/#/releases
https://hisplayer.github.io/UnityiOS-SDK/#/releases
https://hisplayer.github.io/UnityWindows-SDK/#/releases
https://hisplayer.github.io/UnityMacOS-SDK/#/releases

However, the version on the Unity Asset Store is still at 3.4.1.
https://assetstore.unity.com/packages/tools/video/video-streaming-player-for-all-platforms-281535#releases

Do you have plans to update the Unity Asset Store version?

<hr>

[2] I’ve also reviewed your official Unity Features Summary.
https://hisplayer.github.io/UnityFeaturesSummary/#/

It seems that Unity 6 on Android is not yet supported.
Do you have an estimated timeline for adding support?

<hr>

[3] The Unity Asset Store is currently holding a Double 11 Shopping Festival.
Are there any discounts or promotions planned for the "Video Streaming Player for all Platforms"?

Regards.

**Comment by Nusi-22** [comment]
Hello @LoS-Light,

Please see the answers below:

Do you have plans to update the Unity Asset Store version?

-> _Yes, we plan to upgrade our store version in January_

[2] I’ve also reviewed your official Unity Features Summary.
https://hisplayer.github.io/UnityFeaturesSummary/#/

It seems that Unity 6 on Android is not yet supported.
Do you have an estimated timeline for adding support?

-> _We support it already in our premium version. We will support it in the asset store version in January._

[3] The Unity Asset Store is currently holding a Double 11 Shopping Festival.
Are there any discounts or promotions planned for the "Video Streaming Player for all Platforms"?

Regards.

-> Not at the moment, but we have discounts in our video upload platform: https://dashboard.hisplayer.com/signup

**Comment by LoS-Light** [comment]
@Nusi-22 
Thank you very much.

**Comment by LoS-Light** [comment]
That's good to hear.
Thanks for the update.

Nurik ***@***.***> 於 2024年11月12日 週二 上午1:14寫道：
