### ISSUE TITLE
Got warning message : d3d11: Creating a default shader resource view with dxgi-fmt=0 for a texture that uses dxgi-fmt=87

### ISSUE THREAD

**Issue by zoarda** [HISPlayer/Unity_Video_Player#14]
**Describe the issue**
This is a simple project, we create a prefab and attach an extension class inherited from HISPlayerManager.
Set the multi stream property with a render texture and an uploaded webm video to the url
The RawImage is another object of the prefab and assigned to the property.
After start the game in Unity editor and it start streaming a video at background, it shows an error warning as follow :
d3d11: Creating a default shader resource view with dxgi-fmt=0 for a texture that uses dxgi-fmt=87

**Your system and development environment:**
 - HISPlayer Unity Player SDK version:
 - Unity version: 2022.3.50, 2022.3.53 and 2022.3.54
 - Package URL (if purchased from the store): https://assetstore.unity.com/packages/tools/video/video-player-for-all-platforms-281535
 - Operating system (OS): Windows 11
 We also use a plugin called Naninovel
 No matter you set the build to WebGL or standalone Windows, you can see the warning message

**To Reproduce**
Steps to reproduce the issue:
1.Just play the project in Unity editor and it will show the warning message

**Screenshots**
If applicable, could you add screenshots to help explain your problem?

**Comment by Nusi-22** [comment]
Hi @zoarda, thanks for your comment, you can ignore this warning, it wont affect your project. We will remove it in our next release. Let us know if you have any other comment.

**Comment by zoarda** [comment]
understood thanks

**Comment by Nusi-22** [comment]
Hi @zoarda,
Just wanted to let you know that the new version has been released, addressing this warning message. Please feel free to update. 
https://assetstore.unity.com/packages/tools/video/video-player-for-all-platforms-281535

**Comment by zoarda** [comment]
HI @Nusi-22 
After updating from version 3.4.1 to 4.6.1, I encountered a new issue. When using the ChangeVideoContent method to change the URL and waiting for the EventPlaybackReady event to play the video, the behavior has changed.

In version 3.4.1, calling ChangeVideoContent would trigger the EventPlaybackReady event as expected. However, after updating to version 4.6.1, the EventPlaybackReady event is no longer triggered. My script remains unchanged, but it no longer works as intended.

**Comment by zoarda** [comment]
In the setup environment, configure the platform to WebGL.

**Comment by Nusi-22** [comment]
We have tested the SDK 4.6.1 on both editor and WebGL and we cannot reproduce the issue. EventPlaybackReady is always triggered after changing the content using ChangeVideoContent(int playerIndex, string url). Does this issue happen with our HISPlayerSample, included in the SDK?

**Comment by zoarda** [comment]
I tested this issue using the sample project and adjusted the Basic Properties settings to match my project (autoplay = false, loopPlayback = false). With these settings, the issue occurs.

Before the update, the same settings worked fine, but after the update, it seems that autoplay must be enabled for normal operation.

In my project, if I enable autoplay, the video plays, but the EventPlaybackReady event is not triggered.

Could you confirm if this behavior is expected after the update?

Thanks.

**Comment by Nusi-22** [comment]
We still can not reproduce the issue with those playback settings (loop and autoplay set to false). Tested in Windows Editor and WebGL. 
Could you please send over your sample project where the issue occurs to contact@hisplayer.com?

**Comment by Nusi-22** [comment]
We have received it, thanks. 
We will check it and get back to you.

**Comment by zoarda** [comment]
Thanks for checking the code.

Regarding HISPlayerUIHelper.cs, this script will be available once the new version of HISPLAYER_WEBGL is imported into the project. Would you like me to send this version along as well?

For EventSystem, I realize it was missing—sorry about that! I will make sure to include it in the next file submission.
