### ISSUE TITLE
HIS Player - Video is playing upside down on mesh plane

### ISSUE THREAD

**Issue by milkywaystars** [HISPlayer/Unity_Video_Player#2]
We’re using HIS Player to stream play videos on Unity 2021.3.5f1. It works but the video appears updside down(see images and material). 

We have several custom meshes with video playing that works correctly with unity video player but HIS Player is giving problems. 

Changing our existing shader would be a nightmare as it would requires changing UVs for upside down videos.

To recreate: 
1 Add an empty plane 3Dobject. Ensure rotation xyz is 90, 0 ,0
2 Use Unity Video Player to play a video.
3 Swap with Render texture with HIS player Render texture.

**Comment by ivder** [comment]
Hi @milkywaystars , which platform and which SDK version are you using?

**Comment by milkywaystars** [comment]
This issue also occurs on a Canvas raw image and Mesh.
SDK 3.1.1
Platform (OS) - Android Build and Windows Unity Editor. Have not tried IOS.
Unity 2021.3.5f1

-The HISplayer is by far the most stable Player. Not a single crash.
-We temp solved the issue by fixing it in our custom shader and turning the MainTex uv upside-down. We had to rewrite the rest of the shader.
-This issue is now a minor issue for us.

**Comment by ivder** [comment]
@milkywaystars Thank you for the information. You may also set your RawImage Scale Y to -1. For example RawImage game object -> Inspector -> Rect Transform -> Scale X:1 , Y:-1 , Z:1

Additionally for Android only, you may also set `FlipTextureVertically` API to true before setting-up the player. For example : 
```
    protected override void Awake()
    {
        base.Awake();

        // Flip texture vertically
        multiStreamProperties[0].FlipTextureVertically = true;
    }
```

**Comment by milkywaystars** [comment]
Thanks, I'll give this a go.
