### ISSUE TITLE
Can not get hold of support - Player only works for 60 secs

### ISSUE THREAD

**Issue by milkywaystars** [HISPlayer/Unity_Video_Player#3]
We want to extend the play time. The player works flawlessly on DASH.
We tried the contact form https://www.hisplayer.com/contact-unity/ 
We tried the email contact@hisplayer.com
Do you have a phone number? or contact person on LinkedIn?

**Comment by Nusi-22** [comment]
Hi @milkywaystars, Sorry, could you please send us an email to contact@hisplayer.com again? We can't find your previous message.
Btw was our indication to mesh plane helpful?

**Comment by milkywaystars** [comment]
Really sorry to contact you here. I've sent again. Please check the spam.
