### ISSUE TITLE
Audio playback back to Unity AudioSource (2D & 3D spatial audio sound effect)

### ISSUE THREAD

**Issue by GNVR-Dev** [HISPlayer/Unity_Video_Player#4]
Is there any documentation or examples how to set this up?
I purchased Video Streaming Player for Windows and haven't been able to figure it out or find documentation or an example how to do it yet.
Many thanks.

**Comment by Nusi-22** [comment]
Hi @GNVR-Dev, we don’t support spatial audio on Windows in our asset, will add it to our roadmap.

**Comment by GNVR-Dev** [comment]
<img width="1920" alt="UP_SDK" src="https://github.com/HISPlayer/Unity_Video_Player/assets/38672299/74d672e6-cb73-4aad-841a-9dd733f52755">
You should probably clarify that here:

https://hisplayer.com/unity-player-sdk/
which of your Unity products do support that feature?

**Comment by Nusi-22** [comment]
Due to a lack of requirements, we have abandoned this feature. We will add it back to our roadmap. Thanks a lot for pinpointing the source. It is fixed.
