### ISSUE TITLE
Guide for  Amazon Interactive Video Service  set up and Low-Latency support

### ISSUE THREAD

**Issue by GNVR-Dev** [HISPlayer/Unity_Video_Player#5]
I recently purchased Video Streaming Player for Windows and plan to use Amazon Interactive Video Service to create the channel/s that will stream into my Unity application.
I do have the stream working in the Unity Editor but there is a 25 to 30 second gap from the video preview in AWS and what I see in the Editor.
Are there any guides how best to set up Amazon Interactive Video Service inputs and channels for use with Video Streaming Player for Windows.
Amazon mentions that "Amazon IVS low-latency streaming is compatible with most streaming applications and requires only minor changes to your streaming-application configuration."
Notes on reducing Latency are here:
https://docs.aws.amazon.com/ivs/latest/LowLatencyUserGuide/streaming-config.html#streaming-config-reducing-latency
Are these changes able to be implemented in Video Streaming Player for Windows?

**Comment by Nusi-22** [comment]
Hi @GNVR-Dev, we will look into IVS but, in terms of latency, there are other factors such as the length of the segments that will affect it.  There are no special settings on our player side, but maybe on AWS side you should make sure that LL HLS or LL DASH are set. Hope it helps

> I recently purchased Video Streaming Player for Windows and plan to use Amazon Interactive Video Service to create the channel/s that will stream into my Unity application. I do have the stream working in the Unity Editor but there is a 25 to 30 second gap from the video preview in AWS and what I see in the Editor. Are there any guides how best to set up Amazon Interactive Video Service inputs and channels for use with Video Streaming Player for Windows. Amazon mentions that "Amazon IVS low-latency streaming is compatible with most streaming applications and requires only minor changes to your streaming-application configuration." Notes on reducing Latency are here: https://docs.aws.amazon.com/ivs/latest/LowLatencyUserGuide/streaming-config.html#streaming-config-reducing-latency Are these changes able to be implemented in Video Streaming Player for Windows?

Hi, we will look into IVS but, in terms of latency, there are other factors such as the length of the segments that will affect it.  There are no special settings on our player side, but maybe on AWS side you should make sure that LL HLS or LL DASH are set. Hope it helps

**Comment by Nusi-22** [comment]
Hi @GNVR-Dev, we will look into IVS but, in terms of latency, there are other factors such as the length of the segments that will affect it.  There are no special settings on our player side, but maybe on AWS side you should make sure that LL HLS or LL DASH are set. Hope it helps

**Comment by GNVR-Dev** [comment]
Thank you. I will take a look at those settings and see if I can make any improvements.
