### ISSUE TITLE
 Error unable to load video

### ISSUE THREAD

**Issue by ngocchien01tb** [HISPlayer/Unity_Video_Player#8]
I'm using the iOS version but sometimes it fails to load the video and reports the following error "HISPLAYER - ERROR: License checking finished with error: Time out while checking the license key"

**Comment by Nusi-22** [comment]
Hi @ngocchien01tb ,

What HISPlayer SDK version are you using?

**Comment by ngocchien01tb** [comment]
version 3.4.1

**Comment by ngocchien01tb** [comment]
> Hi @ngocchien01tb ,
> 
> What HISPlayer SDK version are you using?

version 3.4.1

**Comment by Nusi-22** [comment]
Dear @ngocchien01tb, 
Now it should work fine, let us know in case this happens again.

**Comment by ngocchien01tb** [comment]
I just got this error again. Please help me check. I am using unity 2022.3.27f1

![image](https://github.com/user-attachments/assets/abf9aa7d-388a-4037-a657-fa569a8837bc)

**Comment by Nusi-22** [comment]
Dear @ngocchien01tb ,
None of our clients are having this issue, it is a bit strange. Could you please try it again one more time, we are checking in parallel.

**Comment by ngocchien01tb** [comment]
> Dear @ngocchien01tb , None of our clients are having this issue, so it is a bit difficult to identify the issue. Could you please try it again? We are checking it in parallel.

I bought it twice with two accounts and tried many times but it didn't work. I bought it but can't find this license key anywhere, can you show me this license key?

**Comment by Nusi-22** [comment]
You do not need to enter any license key. That is only for [HISPlayer SDK Premium version](https://hisplayer.com/contact-hisplayer-unity-sdk-premium/).
We are checking this, we will get back to you.

**Comment by Nusi-22** [comment]
Dear @ngocchien01tb, we will close this issue if you are all set. Thanks.
